### ISSUE TITLE
the file for state_ cannot found in the dataset 

### ISSUE THREAD

**Issue by GavinWB** [HCIS-Lab/RiskBench#1]
state_ = read_json(os.path.join(root,'state',s_type,f"{s_id}_{variant}.json")), 
when load dataset, the file for state_ cannot found in the dataset shared on OneDrive, Can somebody help?

**Comment by GavinWB** [comment]
the issue is in the code of  risk_identification/Baselines/collision-based/dataset/RiskBenchDataset.py,  when define the class RiskBench_dataset(Dataset)

**Comment by chiehchiYang** [comment]
You can download from [here](https://nycu1-my.sharepoint.com/:f:/g/personal/ychen_m365_nycu_edu_tw/EviA5ovlh6hPo_ZXEPQjxAQB2R3vNubk3HM1u4ib1VdPFA?e=WHEWdm) ( **DATA_FOR_Planning_Aware_Metric/metadata.zip** )
You can find the folder named "state". 
Please move this folder inside the dataset folder.
