### ISSUE TITLE
A question about Interactive Risk and Collision Risk

### ISSUE THREAD

**Issue by Zhong-Zi-Zeng** [HCIS-Lab/RiskBench#2]
I have read this paper, which is impressive work. However, I have a question about Interactive Risk and Collision Risk: could you explain their differences? I am a bit confused about this.

Thank you!

**Comment by HankKung** [comment]
Hi, 
Thank you for your interest in our work and sorry for the late response! 
The interactive risk/scenarios indicate the situation where the ego-vehicle yields the risk (e.g., ego-vehicle slows down/stops for a jay-walker). Thus, the two agents could be in near collision but not collide with each other.

Thank you!
