### ISSUE TITLE
Abnormal dataset download

### ISSUE THREAD

**Issue by xinxinlv** [HCIS-Lab/RiskBench#3]
Hi there! I want to express my admiration for your excellent work on this repository. I encountered an issue when downloading the 'riskbench_dataset'. I was only able to successfully download approximately 2GB. However, when attempting to extract the data, an error occurred. The error message is as follows:
"The file size exceeds the allowed limit. Correlationld: d88401b1-6212-4d74-b80d-fc6deea869f1, UTC DateTime: 08/26/2024 10:53:46"

I would greatly appreciate it if you could assist me in resolving this problem. Thank you.

**Comment by chiehchiYang** [comment]
we will update new dataset link. (  Split folder into Multiple Files tar of 2Gb file size )

**Comment by xinxinlv** [comment]
> we will update new dataset link. ( Split folder into Multiple Files tar of 2Gb file size )

Thank you for your reply. If it's feasible, that would be fantastic. I'm also attempting to download the compressed packages one by one separately. Haha, it will be a bit slow.

**Comment by chiehchiYang** [comment]
Please check this link: 
https://nycu1-my.sharepoint.com/:f:/g/personal/ychen_m365_nycu_edu_tw/Ekv-ljiKGVJHmXaiSUCYTjoBbr-1fS5BGf3Vk7v5r5WxBg?e=IVteE6
